export const COURSES_DATA = [
  {
    id: "CS101",
    code: "CS 101",
    name: "Intro to Computer Science",
    avgHours: 12.5,
    stdDev: 3.1,
    credits: 4,
    dept: "CS",
    professor: "Prof. Chen",
    responses: 142,
  },
  {
    id: "MATH201",
    code: "MATH 201",
    name: "Linear Algebra",
    avgHours: 10.2,
    stdDev: 2.4,
    credits: 3,
    dept: "MATH",
    professor: "Prof. Patel",
    responses: 89,
  },
  {
    id: "HIST300",
    code: "HIST 300",
    name: "Modern World History",
    avgHours: 6.5,
    stdDev: 1.8,
    credits: 3,
    dept: "HIST",
    professor: "Prof. Rivera",
    responses: 45,
  },
  {
    id: "PHYS150",
    code: "PHYS 150",
    name: "Physics I: Mechanics",
    avgHours: 14.8,
    stdDev: 3.6,
    credits: 4,
    dept: "PHYS",
    professor: "Prof. Nguyen",
    responses: 112,
  },
  {
    id: "ENG102",
    code: "ENG 102",
    name: "Academic Writing",
    avgHours: 5.5,
    stdDev: 1.5,
    credits: 3,
    dept: "ENG",
    professor: "Prof. Williams",
    responses: 230,
  },
  {
    id: "CHEM210",
    code: "CHEM 210",
    name: "Organic Chemistry",
    avgHours: 18.2,
    stdDev: 4.2,
    credits: 5,
    dept: "CHEM",
    professor: "Prof. Kim",
    responses: 98,
  },
  {
    id: "CS201",
    code: "CS 201",
    name: "Data Structures",
    avgHours: 15.5,
    stdDev: 3.9,
    credits: 4,
    dept: "CS",
    professor: "Prof. Johnson",
    responses: 120,
  },
  {
    id: "ART100",
    code: "ART 100",
    name: "Intro to Painting",
    avgHours: 8.2,
    stdDev: 2.0,
    credits: 2,
    dept: "ART",
    professor: "Prof. Garcia",
    responses: 34,
  },
];